%BuildOptions = (%BuildOptions,
    NAME                => 'Dancer::Plugin::Transformator',
    DISTNAME            => 'Dancer-Plugin-Transformator',
    AUTHOR              => 'David Zurborg <zurborg@cpan.org>',
    VERSION_FROM        => 'lib/Dancer/Plugin/Transformator.pm',
    ABSTRACT_FROM       => 'lib/Dancer/Plugin/Transformator.pm',
    LICENSE             => 'ISC',
	META_MERGE          => {
		resources => {
			homepage   => 'https://metacpan.org/release/Dancer-Plugin-Transformator',
			repository => 'https://github.com/zurborg/libdancer-plugin-transformator-perl.git',
			bugtracker => 'https://github.com/zurborg/libdancer-plugin-transformator-perl/issues',
		},
	},
    PL_FILES            => {},
    PMLIBDIRS           => [qw[ lib ]],
    PREREQ_PM           => {
        'Test::More'        => 0,
        'Modern::Perl'      => 0,
		'Dancer'            => 1.3132,
		'Net::NodeTransformator' => 0.101,
		'IPC::Run'          => 0,
		'Try::Tiny'         => 0,
		'Env::Path'         => 0.19,
    },
    dist                => {
        COMPRESS            => 'gzip -9f',
        SUFFIX              => 'gz',
        CI                  => 'git add',
        RCS_LABEL           => 'true',
    },
    clean               => { FILES => 'Dancer-Plugin-Transformator-*' },
    depend              => {
		'$(FIRST_MAKEFILE)' => 'config/BuildOptions.pm',
    },
);
